### ISSUE TITLE
Ease embedability by reducing main package content

### ISSUE THREAD

**Issue by thomasf** [Yawning/obfs4#12]
I'm embedding obfs4proxy inside another go program.

Right now I just copied the main package to my own package, renamed the `main` functtion to `Run` and replaced everything flag related with an config struct..

Would you accept a pull request moving most of the main package into `common/obfs4proxy`?

It's not super important but it does result in a nicer reuse situation.

My quick hack looks lite this:

```go
type Config struct {
	ShowVer       bool
	LogLevel      string
	EnableLogging bool
	UnsafeLogging bool
}

func Run(config Config) {
	// Initialize the termination state monitor as soon as possible.
	termMon = newTermMonitor()

	// Handle the command line arguments.
	_, execName := path.Split(os.Args[0])
	// showVer := flag.Bool("version", false, "Print version and exit")
	// logLevelStr := flag.String("logLevel", "ERROR", "Log level (ERROR/WARN/INFO/DEBUG)")
	// enableLogging := flag.Bool("enableLogging", false, "Log to TOR_PT_STATE_LOCATION/"+obfs4proxyLogFile)
	// unsafeLogging := flag.Bool("unsafeLogging", false, "Disable the address scrubber")
	// flag.Parse()

	logLevel := config.LogLevel
	if logLevel == "" {
		logLevel = "ERROR"
	}
...
```

**Comment by chrisballinger** [comment]
@thomasf We would like to include obfs4 inside a future release of Tor for iOS which will require a very similar change. I still need to investigate the best way to invoke a Go library from C, but it should be more feasible given that Go 1.5 now supports iOS/ARM cross compilation.

**Comment by Yawning** [comment]
Sorry for ignoring this for a while.  I really should just close the github issue tracker since, the only reason a copy of the code lives here is so I can keep feature branches somewhere.

This is not a use-case I want to support since the code that lives under `main` is not and will not be written with embeddability in mind (and in fact currently will do rather unexpected things when the process gets re-parented for example).

I would be open to carving out things from the `main` package into sub-packages under `common` (eg: `common/socks5`, `common/termmon`) which may aid in code reuse, but the actual pt implementation already provides a well defined external interface based on `fork() + exec()`, and that's all I'm currently willing to support.
