### ISSUE TITLE
failed to connect to ORPort: dial: connection refued

### ISSUE THREAD

**Issue by biaocy** [Yawning/obfs4#14]
Hi, Yawning. First of all, thank you for the creation of the project.
When I use this project, encountered the following issues, can you help me look at it?
```
2015/09/01 10:11:44 [NOTICE]: obfs4proxy-0.0.6-dev - launched
2015/09/01 10:13:07 [ERROR]: obfs4([scrubbed]:35534) - failed to connect to ORPort: dial: connection refused
2015/09/01 10:13:09 [ERROR]: obfs4([scrubbed]:35538) - failed to connect to ORPort: dial: connection refused
2015/09/01 10:13:11 [ERROR]: obfs4([scrubbed]:35548) - failed to connect to ORPort: dial: connection refused
2015/09/01 10:13:11 [ERROR]: obfs4([scrubbed]:35552) - failed to connect to ORPort: dial: connection refused
```

**Comment by thomasf** [comment]
Unless you are using obfs4proxy with TOR you need to read the TOR Pluggable Transport spec https://gitweb.torproject.org/torspec.git/tree/pt-spec.txt and see how you can integrate it with other things. The error message your getting is probably due to the fact the destination of your TOR_PT_ORPORT probably isn't accepting connections

**Comment by biaocy** [comment]
@thomasf 
You'r right, I use this project https://github.com/gumblex/ptproxy to integrate obfs4 with shadowsocks.In my case, my server side shadowsocks's configuration was wrong, I have resolved it.Thank you for your help.
