### ISSUE TITLE
MTU for china

### ISSUE THREAD

**Issue by Huangdong2** [Yawning/obfs4#26]
i'm from china, harbin
can you please improve the code for obfsproxy or obfs4 to have MTU paramter for using from china?
for example to have "ServerTransportOptions scramblesuit MTU=1480" in torrc
for the link mtu, the python code hardcoded this value as 1500, that's not suitable for china i think

**Comment by Yawning** [comment]
No, because that would require updating the bridge code, there's no provisions for protocol version negotiation in either protocol and thus would introduce compatibility problems.  The "MTU" is kind of arbitrary anyway, since the kernel's TCP/IP stack will do whatever it wants.

It's something I'll think about when i design obfs5.

WONTFIX.

**Comment by Huangdong2** [comment]
thx for the reply, but i'm afraid of segmented packets will pass back and forth to china
like i encounted now from tor browser, when i click a button on a page the progress bar reached almost the end, but stuck

**Comment by Huangdong2** [comment]
i'm now using a private bridge in tokyo, would you like to have it? i will give it to u for evaluation my bridge

**Comment by Huangdong2** [comment]
and i'm googling now for a few days for how to have my openvpn to socks it

**Comment by louy2** [comment]
Since now you have a private bridge, you can just fork this and change the hardcoded value to one you think is appropriate.
